[config_names]
  intel_cy50t2_alaro = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209"
  intel_cy50t2_alaro_climate_files = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_climate_files"
  intel_cy50t2_alaro_ddh = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_ddh"
  intel_cy50t2_alaro_eps = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_eps"
  intel_cy50t2_alaro_mode_start = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_mode_start"
  intel_cy50t2_arome = "feature_activate_reference_checker_intel_CY50t2_AROME_DEMO_60x80_2500m_20250209"
  intel_cy50t2_arome_climate_files = "feature_activate_reference_checker_intel_CY50t2_AROME_DEMO_60x80_2500m_20250209_climate_files"
  intel_cy50t2_arome_ddh = "feature_activate_reference_checker_intel_CY50t2_AROME_DEMO_60x80_2500m_20250209_ddh"
  intel_cy50t2_arome_eps = "feature_activate_reference_checker_intel_CY50t2_AROME_DEMO_60x80_2500m_20250209_eps"
  intel_cy50t2_arome_mode_start = "feature_activate_reference_checker_intel_CY50t2_AROME_DEMO_60x80_2500m_20250209_mode_start"
  intel_cy50t2_arome_target = "feature_activate_reference_checker_intel_CY50t2_AROME_DEMO_80x90_1000m_20250209"
  intel_cy50t2_compile = "feature_activate_reference_checker_intelCY50t2_compile"
  intel_cy50t2_harmonie_arome = "feature_activate_reference_checker_intel_CY50t2_HARMONIE_AROME_DEMO_60x80_2500m_20250209"
  intel_cy50t2_harmonie_arome_climate_files = "feature_activate_reference_checker_intel_CY50t2_HARMONIE_AROME_DEMO_60x80_2500m_20250209_climate_files"
  intel_cy50t2_harmonie_arome_ddh = "feature_activate_reference_checker_intel_CY50t2_HARMONIE_AROME_DEMO_60x80_2500m_20250209_ddh"
  intel_cy50t2_harmonie_arome_eps = "feature_activate_reference_checker_intel_CY50t2_HARMONIE_AROME_DEMO_60x80_2500m_20250209_eps"
  intel_cy50t2_harmonie_arome_mode_start = "feature_activate_reference_checker_intel_CY50t2_HARMONIE_AROME_DEMO_60x80_2500m_20250209_mode_start"
  intel_cy50t2_harmonie_arome_target = "feature_activate_reference_checker_intel_CY50t2_HARMONIE_AROME_DEMO_80x90_1000m_20250209"
