[archiving.FDB.fdb.fpgrib_files]
  active = false

[cleaning.PostMortem.ecf_files]
  active = false

[fdb.expver_restrictions]
  test = ["snh02", "lrb_465000527_efdev"]

[general]
  case = "@CASE_PREFIX@_@CYCLE@_@CSC@_@DOMAIN@_@YMD_START@@CASE_SUFFIX@"

[general.times]
  cycle_length = "PT3H"
  end = "PT3H"
  forecast_range = "PT3H"
  start = "2025-02-09T00:00:00Z"

[macros.select.release_test]
  os_macros = ["PERM"]

[platform]
  ref_case = "intel_@CYCLE@_@CSC@_@DOMAIN@_@YMD_START@@CASE_SUFFIX@"
  reference_data = "@SCRATCH@/@SYS_NAME@/@CYCLE@"
  reference_tag = "v1.1.0"
  references_folder = "@SCRATCH@/tactus_references/@REFERENCE_TAG@"
  references_generation_folder = "N/A"

[platform.mirrorglobalDT]
  remote_host = "ecflow-gen-snh02-001"
  remote_path = "/mirror_globalDT_iekm/pabv/iekm/fc/main/fcgroup/00/model"

[reference_checker]
  check = true
  generate = false
  rules_active = ["Forecast.fullpos", "Forecast.history", "Forecast.log"]
  suppress_exception = false

[reference_checker.task.Forecast]

[reference_checker.task.Forecast.fullpos]
  generate_folder = "@REFERENCES_GENERATION_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"
  inpath = "@ARCHIVE@"
  method = "FullPosFields"
  pattern = "GRIBPF.*0003h00m00s"
  reference_folder = "@REFERENCES_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"

[reference_checker.task.Forecast.history]
  generate_folder = "@REFERENCES_GENERATION_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"
  inpath = "@ARCHIVE@"
  method = "HistoryFields"
  pattern = "ICMSH.*0003h00m00s"
  reference_folder = "@REFERENCES_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"

[reference_checker.task.Forecast.log]
  generate_folder = "@REFERENCES_GENERATION_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"
  inpath = "@WRK@/logs/Forecast"
  method = "ForecastNorms"
  pattern = "NODE.001_01"
  reference_folder = "@REFERENCES_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"

[reference_checker.task.Forecast.surfex]
  generate_folder = "@REFERENCES_GENERATION_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"
  inpath = "@ARCHIVE@"
  method = "HistoryFields"
  pattern = "ICMSH.*0003h00m00s.sfx"
  reference_folder = "@REFERENCES_FOLDER@/@REF_CASE@/@ARCHIVE_TIMESTAMP@/@MEMBER_STR@"
  result_folder = "@WRK@/checks/Forecast"

[scheduler]

[scheduler.ecfvars]
  case_prefix = "feature_activate_reference_checker_intel"
  ecf_files = "@PERM@/tactus_ecflow/ecf_files"
  ecf_files_remotely = "@PERM@/tactus_ecflow/ecf_files"
  ecf_home = "@PERM@/tactus_ecflow/jobout"
  ecf_jobout = "@PERM@/tactus_ecflow/jobout"
  ecf_out = "@PERM@/tactus_ecflow/jobout"

[scheduler.mirror_suite]
  mirror_name = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_climate_files"
  remote_path = "/feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_climate_files/PostMortem"

[submission]
  bindir = "@SCRATCH@/@SYS_NAME@/@CASE_PREFIX@@CYCLE@_compile/install/R64/bin"
  bindir_gl = "@SUBMISSION.BINDIR@"
  max_ecf_tasks = 5

[submission.task_exceptions]

[submission.task_exceptions.Forecast]
  bindir = "@SUBMISSION.BINDIR@"

[submission.task_exceptions.PgdFilterTownFrac.ENV]
  ECF_TRIES = 15

[suite_control]
  compile = false
  create_static_data = false
  do_archiving = false
  mirror_suite = true
  mode = "start"

[system]
  case_suffix = "_mode_start"
  climdir = "@REFERENCE_DATA@/@CASE_PREFIX@/cy50t2_alaro/climate/@DOMAIN@"
  host_case = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_climate_files"
  host_domain = "DEMO_60x80_2500m"
  host_suite = "feature_activate_reference_checker_intel_CY50t2_ALARO_DEMO_60x80_2500m_20250209_climate_files"
  test_data_path = "/perm/snh/ttr/data"
