name: Build and Deploy Documentation
on:
  push:
    branches:
      - master
      - develop
    paths:
      - '**.py'
      - '*.rst'
      - '*.md'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - '**.py'
      - '*.rst'
      - '*.md'
  release:
    types: [published]
  workflow_dispatch:

permissions:
    contents: write

jobs:
  docs:
    if: github.repository_owner == 'destination-earth-digital-twins'
    name: Generate API Documentation
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_READ_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set github credentials
        uses: ./.github/actions/setup-github-credentials
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: latest

      - name: Install dependencies with Pixi
        run: |
          pixi install
          pixi run bootstrap

      - name: Build documentation
        run: pixi run make doc-build

      - name: Deploy to https://github.com/destination-earth-digital-twins/deode-workflow-docs
        if: ${{ github.event_name == 'published' }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'docs/_build/'
          destination-repository-name: 'destination-earth-digital-twins/deode-workflow-docs'
          target-branch: gh-pages
          target-directory: docs/
          user-name: Deode Workflow API Doc Builder
          user-email: Deode-Workflow@noreply.github.com
