#.github/workflows/tests.yaml
name: Unit Tests

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    if: github.repository_owner == 'destination-earth-digital-twins'
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        env: [ "pytest" ]
        python-version: [ "3.10" ]

    name: "Unit-tests ${{ matrix.os }}, python=${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_READ_TOKEN }}

    container:
      image: python:${{ matrix.python-version }}-bullseye
      env:
        COVERAGE_FILE: ".coverage.${{ matrix.env }}.${{ matrix.python-version }}"

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set github credentials
        uses: ./.github/actions/setup-github-credentials
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Install Pixi and dependencies
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          run-install: true
          post-cleanup: true
          frozen: true
          cache: true

      - name: Install additional dependency groups
        run: |
          pixi run bootstrap

      - name: Run tests
        run: pixi run pytest -n auto --maxprocesses 16


      # Disable upload to codecov until/if codecov is enabled
      # - name: Upload test coverage report to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./.coverage.xml
