#.github/workflows/tests.yaml
name: Unit Tests

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    if: github.repository_owner == 'ACCORD-NWP'
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.14" ]

    name: "Unit-tests ${{ matrix.os }}, python=${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_READ_TOKEN }}
    container:
      image: python:${{ matrix.python-version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set github credentials
        uses: ./.github/actions/setup-github-credentials
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Install ping
        run: |
          apt-get update
          apt-get install -y inetutils-ping

      - name: Install Pixi and dependencies
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          run-install: true
          manifest-path: pyproject.toml
          post-cleanup: true
          frozen: true
          cache: true
          auth-token: ${{ secrets.GH_REPO_READ_TOKEN }}
          activate-environment: true
          environments: test

      - name: Run tests
        run: pixi run test


      # Disable upload to codecov until/if codecov is enabled
      # - name: Upload test coverage report to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./.coverage.xml
